export const oficinasPredeterminadas = [
  {
    nombre: 'SUBSECRETARÍA TÉCNICA, ADMINISTRATIVA Y LEGAL',
    dependencias: ['DIRECCIÓN GENERAL DE ADMINISTRACIÓN', 'DIRECCIÓN GENERAL TÉCNICA Y LEGAL']
  },
  {
    nombre: 'DIRECCIÓN GENERAL DE ADMINISTRACIÓN',
    dependencias: ['DIRECCIÓN DE CONTABILIDAD', 'DIRECCIÓN DE PRESUPUESTO', 'DIRECCIÓN DE COMPRAS, CONTRATACIONES Y SUMINISTROS', 'DIRECCION DE TESORERIA', 'DIRECCION DELEGADA DE LA DIRECCION PROVINCIAL DE PERSONAL', 'DIRECCIÓN DE TECNOLOGÍA DE LA INFORMACIÓN', 'DIRECCION DE SERVICIOS AUXILIARES', 'DIRECCION DE SERVICIOS TECNICOS']
  },
  {
    nombre: 'DIRECCIÓN GENERAL TÉCNICA Y LEGAL',
    dependencias: ['DIRECCIÓN TÉCNICO ADMINISTRATIVA', 'DIRECCIÓN DE COORDINACIÓN JURÍDICA', 'DIRECCION DE GESTION DE MULTAS POR INFRACCIONES DE TRANSITO Y TRANSPORTE']
  },
  {
    nombre: 'SUBSECRETARÍA DE TRANSPORTE TERRESTRE',
    dependencias: ['DIRECCIÓN PROVINCIAL DE FISCALIZACION DEL TRANSPORTE', 'DIRECCIÓN PROVINCIAL DE TRANSPORTE DE PASAJEROS', 'DIRECCIÓN PROVINCIAL DE TRANSPORTE DE CARGAS', 'DIRECCIÓN PROVINCIAL DE APTITUD PSICOFISICA PARA CONDUCTORES DEL TRANSPORTE', 'DIRECCIÓN PROVINCIAL DE TRANSPORTE SOSTENIBLE', 'DIRECCIÓN PROVINCIAL DE VERIFICACION TECNICA VEHICULAR']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE FISCALIZACION DEL TRANSPORTE',
    dependencias: ['DIRECCIÓN DE CONTROL TECNICO', 'DIRECCIÓN DE RECLAMOS Y SOLICITUDES']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE TRANSPORTE DE PASAJEROS',
    dependencias: ['DIRECCIÓN DE TRANSPORTE AUTOMOTOR DE PASAJEROS', 'DIRECCIÓN DE PERMISOS Y HABILITACIONES DE TRANSPORTE DE PASAJEROS', 'DIRECCION DE TRANSPORTE FERROVIARIO DE PASAJEROS']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE TRANSPORTE DE CARGAS',
    dependencias: ['DIRECCIÓN DE PERMISOS Y HABILITACIONES DE TRANSPORTE DE CARGAS', 'DIRECCIÓN DE TRANSPORTE DE AUTOMOTOR DE CARGAS', 'DIRECCION DE TRANSPORTE FERROVIARIO DE CARGAS']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE APTITUD PSICOFISICA PARA CONDUCTORES DEL TRANSPORTE PUBLICO',
    dependencias: ['DIRECCIÓN DE COORDINACION DEL SERVICIO DE EVALUACION PSICOFISICA', 'DIRECCIÓN DE CONTRALOR Y MONITOREO DE EVAOLUACION PSICOFISICA']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE POLITICAS DE TRANSPORTE SOSTENIBLE',
    dependencias: ['DIRECCIÓN DE DESARROLLO SOSTENIBLE DEL TRANSPORTE', 'DIRECCIÓN DE PROYECTOS ESTRATEGICOS']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE VERIFICACION TECNICA VEHICULAR',
    dependencias: ['DIRECCIÓN DE APOYO LEGAL Y TECNICO ADMINISTRATIVO', 'DIRECCIÓN DE PLANIFICACION Y COORDINACION DEL SERVICIO', 'DIRECCIÓN DE FISCALIZACION Y CONTROL']
  },
  {
    nombre: 'SUBSECRETARÍA DE POLITICA Y SEGURIDAD VIAL',
    dependencias: ['DIRECCIÓN PROVINCIAL DE LICENCIAS DE CONDUCIR Y ANTECEDENTES DE TRANSITO', 'DIRECCIÓN PROVINCIAL DE OBSERVATORIO VIAL', 'DIRECCIÓN PROVINCIAL DE FISCALIZACION Y CONTROL DEL TRANSITO Y LA SEGURIDAD VIAL', 'DIRECCIÓN PROVINCIAL DE APOYO Y COORDINACION TECNICO ADMINISTRATIVA']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE LICENCIAS DE CONDUCIR Y ANTECEDENTES DE TRANSITO',
    dependencias: ['DIRECCIÓN DE LICENCIAS DE CONDUCIR', 'DIRECCIÓN DE ANTECEDENTES E INHABILITADOS']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE OBSERVATORIO VIAL',
    dependencias: ['DIRECCIÓN DE ESTADISTICA VIAL', 'DIRECCIÓN DE CAPACITACION Y ENLACE COMUNITARIO']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE FISCALIZACION Y CONTROL DEL TRANSITO Y LA SEGURIDAD VIAL',
    dependencias: ['DIRECCIÓN DE FISCALIZACION Y CONTROL DEL TRANSITO Y LA SEGURIDAD VIAL']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE APOYO Y COORDINACION TECNICO ADMINISTRATIVA',
    dependencias: ['JUZGADOS ADMINISTRATIVOS DE INFRACCIONES DE TRANSITO PROVINCIAL (I A XIII) ', 'DIRECCIÓN DE APOYO ADMINISTRATIVO', 'DIRECCION DE COORDINACION Y ORGANIZACIÓN DE LA JUSTICIA ADMINISTRATIVA DE INFRACCIONES DE TRANSITO PROVINCIAL', 'DIRECCION DE INFORMATICA Y TECNOLOGIA']
  },
  {
    nombre: 'SUBSECRETARÍA DE TRANSPORTE AEREO Y FLUVIAL',
    dependencias: ['DIRECCIÓN PROVINCIAL DE CONTRALOR DEL TRANSPORTE FLUVIAL DE PASAJEROS', 'DIRECCIÓN PROVINCIAL DE CONTRALOR DEL TRANSPORTE AEREO', 'DIRECCIÓN PROVINCIAL DE PROMOCION Y COORDINACION DEL TRANSPORTE AEREO Y FLUVIAL']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DEL CONTRALOR DEL TRANSPORTE FLUVIAL DE PASAJEROS',
    dependencias: ['DIRECCIÓN DE OPERACIONES DE TRANSPORTE FLUVIAL DE PASAJEROS', 'DIRECCIÓN DE FISCALIZACION DEL TRANSPORTE FLUVIAL DE PASAJEROS']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE CONTRALOR DEL TRANSPORTE AEREO',
    dependencias: ['DIRECCIÓN DE OPERACIONES DE TRANSPORTE AEREO', 'DIRECCION DE FISCALIZACION AEROPORTUARIA']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE PROMOCION Y COORDINACION DEL TRANSPORTE AEREO Y FLUVIAL ',
    dependencias: ['DIRECCIÓN DE ESTRATEGIAS PORTUARIAS Y AEROPORTUARIAS', 'DIRECCIÓN DE PROMOCION Y DESARROLLO DEL TRANSPORTE FLUVIAL DE PASAJEROS']
  },
  {
    nombre: 'SUBSECRETARÍA DE ARTICULACION INTERJURISDICCIONAL DEL TRANSPORTE',
    dependencias: ['DIRECCIÓN PROVINCIAL DE COMPENSACIONES AL TRANSPORTE', 'DIRECCIÓN PROVINCIAL DE COORDINACION DEL TRANSPORTE', ' DIRECCION PROVINCIAL DE PLANIFICACION Y POLITICA ECONOMICA DEL TRANSPORTE ', 'DIRECCION PROVINCIAL DE POLITICAS DE GENERO Y ESTRATEGIAS INCLUSIVAS ', 'DIRECCION PROVINCIAL DE POLITICAS EDUCATIVAS DE PREVECION']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE COMPENSACIONES AL TRANSPORTE',
    dependencias: ['DIRECCIÓN DE LIQUIDACION Y PAGO', 'DIRECCION DE CONTROL Y VERIFICACION']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE COORDINACION DEL TRANSPORTE',
    dependencias: ['DIRECCIÓN DE COORDINACION DEL TRANSPORTE CON EL SECTOR PUBLICO', 'DIRECCIÓN DE COORDINACIÓN DEL TRANSPORTE CON EL SECTOR PRIVADO']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE PLANIFICACION Y POLITICA ECONOMICA DEL TRANSPORTE',
    dependencias: ['DIRECCIÓN DE PLANIFICACION DEL TRANSPORTE', 'DIRECCIÓN DE ANALISIS EFICIENTE DEL TRANSPORTE', 'DIRECCION DE GESTION DE SUBSIDIOS AL TRANSPORTE']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE POLITICAS DE GENERO Y ESTRATEGIAS INCLUSIVAS',
    dependencias: ['DIRECCIÓN DE ACCESIBILIDAD DEL TRANSPORTE', 'DIRECCIÓN DE INCLUSION Y DIVERSIDAD']
  },
  {
    nombre: 'DIRECCIÓN PROVINCIAL DE POLITICAS EDUCATIVAS DE PREVENCION',
    dependencias: ['DIRECCIÓN DE PROMOCION DE NORMAS DE CONVIVENCIA CIUDADANA', 'DIRECCIÓN DE GESTION INTERMINISTERIAL DE PREVENCION Y CONCIENTIZACION EN EL TRANSPORTE']
  },
  {
    nombre: 'UNIDAD DE MONITOREO Y REGISTRO GENERAL DE DATOS DEL TRANSPORTE',
    dependencias: []
  },
  {
    nombre: 'DIRECCION DE COMUNICACIÓN Y RELACIONES INSTITUCIONALES',
    dependencias: []
  }
];