export const oficinasPredeterminadas = [
  {
    nombre: 'SUBSECRETARÍA TÉCNICA, ADMINISTRATIVA Y LEGAL',
    dependencias: ['DIRECCIÓN GENERAL DE ADMINISTRACIÓN', 'DIRECCIÓN GENERAL TÉCNICA Y LEGAL']
  },
  {
    nombre: 'DIRECCIÓN GENERAL DE ADMINISTRACIÓN',
    dependencias: ['DIRECCIÓN DE CONTABILIDAD', 'DIRECCIÓN DE PRESUPUESTO', 'DIRECCIÓN DE COMPRAS, CONTRATACIONES Y SUMINISTROS', 'DIRECCIÓN DE TECNOLOGÍA DE LA INFORMACIÓN']
  },
  {
    nombre: 'DIRECCIÓN GENERAL TÉCNICA Y LEGAL',
    dependencias: [ 'DIRECCIÓN TÉCNICO ADMINISTRATIVA', 'DIRECCIÓN DE COORDINACIÓN JURÍDICA']
  }
];